import Card from '@/ui-kit/Card/Card';
import React from 'react';
import style from './Security.module.css';

const Security = (): JSX.Element => {
  return (
    <>
      <h2 className={style.header}>Security</h2>
      <div className={style.wrap}>
        <Card className={style.gridThreshold}>
          <div className={style.contentWrap}>
            <h3 className={style.title}>Threshold signature</h3>
            <p className={style.content}>
              The signatures are generated by making multiple independent parties communicate to each other, each party
              having it's own secret key.
            </p>
          </div>
        </Card>

        <Card className={style.gridTSS}>
          <div className={style.contentWrap}>
            <h3 className={style.title}>Set up your OWN TSS signer</h3>
            <p className={style.content}>
              {'Trustless administration via a set of smart contracts & convenient key generation and rotation.'}
            </p>
          </div>
        </Card>
      </div>
    </>
  );
};

export default React.memo(Security);
