export enum ModalType {
  MERCHANT_ADD_ENDPOINT = 'MERCHANT_ADD_ENDPOINT',
  MERCHANT_SHARED_SECRET = 'MERCHANT_SHARED_SECRET',
  MERCHANT_WALLET_ADDRESS = 'MERCHANT_WALLET_ADDRESS',
  PAYMENT_CONNECT_WALLET = 'PAYMENT_CONNECT_WALLET',
  SETUP_TWO_FACTOR_AUTH = 'SETUP_TWO_FACTOR_AUTH'
}

export type OpenModalInput = {
  modalType: ModalType;
};
