version: '3'

services:
  tss-client:
    image: tss-client
    container_name: tss-client
    restart: always 
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NPM_TOKEN: $NPM_TOKEN
    volumes:
     - ./tss-key-shares:/tss-client/tss-key-shares
    ports:
     - $PORT:$PORT