export enum FailedToCreateUserException {
	USER_IS_ALREADY_ACTIVE = 'USER_IS_ALREADY_ACTIVE',
	USER_IS_ALREADY_AFFILIATED = 'USER_IS_ALREADY_AFFILIATED',
	WRONG_AFFILIATED_ID = 'WRONG_AFFILIATED_ID',
	INTERNAL_ERROR = 'INTERNAL_ERROR'
}
